### ISSUE TITLE
mpfr_get_str returns too many digits

### ISSUE THREAD

**Issue by SanderBouwhuis** [BrianGladman/mpfr#1]
I am probably doing something wrong, but I'm getting many useless digits when converting an mpfr to string.
The idea is to let mpfr 'automatically' choose the correct amount of useful decimals.

I set a string with mpfr_strtofr and extract a string with mpfr_get_str.

```
void Test()
{
  CBigFloat bfTest("3.141592653589793238462643383280");
  char      pcResult[1024]{};

  // Convert to string, but don't specify how many digits we want (we should automatically get a sensible amount)
  bfTest.ToString(pcResult, _countof(pcResult));
}
```

The result is : "3.141592653589793238462643383280000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003".
I want/expected something like this : "3.14159265358979323846264338328"

I sort of do it like this (cobbled together code, not the actual implementation!).

```
// Constructor
explicit CBigFloat(const char *pcNum)
{
  mpfr_init2(m_mpfr, 1024);

  uint32 u32Len = 0;

  // Clear the current value
  mpfr_set_zero(m_mpfr, 0);

  // Do we have valid parameters?
  if(pcNum)
  {
    char *pcEnd = nullptr;

    // Get the number
    mpfr_strtofr(m_mpfr, pcNum, &pcEnd, 10, MPFR_RNDN);

    // Get the length
    if(pcEnd >= pcNum)
      u32Len = uint32(pcEnd - pcNum);
  }

  // Should we store the length?
  if(pu32Len)
    *pu32Len = u32Len;
    
  return *this;
}


//--------------------------------------------------------------------------------------------------


// This function returns the value as a string
constexpr char* CBigFloat::ToString(char *pcBigFloat, uint32 u32MaxChars, int32 i32TotDecimals /* -1 */, uint32 *pu32Len /* nullptr */) const
{
  int32 i32Len = 0;

  // Do we have valid parameters?
  if(pcBigFloat  &&  u32MaxChars > 0)
  {
    char pcFormat[32]{};

    // Get the floating point as string
    if(Safe_snprintf(pcFormat, _countof(pcFormat), "%%.%iRNf", i32TotDecimals >= 0 ? i32TotDecimals : GetTotSignificantDecimals()) > 0)
      i32Len = mpfr_snprintf(pcBigFloat, u32MaxChars, pcFormat, m_mpfr);

    // Don't we have a valid string?
    if(i32Len <= 0)
    {
      // Make sure the string is zero terminated
      pcBigFloat[0] = '\0';
      i32Len = 0;
    }
  }

  // Should we store the length?
  if(pu32Len)
    *pu32Len = i32Len;

  return pcBigFloat;
}


//--------------------------------------------------------------------------------------------------


// This function determines the actual significant decimals needed to display the value
uint32 CBigFloat::GetTotSignificantDecimals()
{
  char      *pcDigits;
  mpfr_exp_t expWholeNumberLen;
  
  // Get the string
  pcDigits = mpfr_get_str(nullptr, &expWholeNumberLen, 10, 0, m_mpfr, MPFR_RNDN);
  u32TotDecimals = Safe_strlen(pcDigits);
  
  // Remove the digits before the decimal point
  if(expWholeNumberLen < 0)
    u32TotDecimals -= expWholeNumberLen;
  else if(static_cast<uint32>(expWholeNumberLen) < u32TotDecimals)
    u32TotDecimals -= expWholeNumberLen;
  else
    u32TotDecimals = 0;
  
  // Free the resources
  mpfr_free_str(pcDigits);
}
```

**Comment by BrianGladman** [comment]
When you set the value you asked for a precision of 1024 bits and this will give a result as close as possible to your input value using this number of bits.    When you use mpfr_get_str(), you are setting the parameter 'n'  as zero,  which means that you are asking for an output which, if subsequently used for input, will give **exactly** the value given to mpfr_get_str()  (notice the '3' at the end).    To avoid this just set 'n' to the number of digits you want in the output.

**Comment by SanderBouwhuis** [comment]
We have a misunderstanding. I should not have used π. It was about a string with a limited/fixed length.
Assume something random like : "3.4" + "7.238" + "23.1" + "19.5432". Here, there are a maximum of 6 digits. This can be represented perfectly as "53.2812"

```
CBigFloat bfResult;
char      pcResult[1024]{};

bfResult = CBigFloat("3.4") + CBigFloat("7.238") + CBigFloat("23.1") + CBigFloat("19.5432");
bfResult.ToString(pcResult, _countof(pcResult));

```

This results in "53.28119999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999968"

Is there a way to detect that the result should be rounded to "53.2812"?
Every calculator on Earth will give you this number, but how do I make mpfr give me this number?

**Comment by BrianGladman** [comment]
> We have a misunderstanding. I should not have used π. It was about a string with a limited/fixed length.
> Assume something random like : "3.4" + "7.238" + "23.1" + "19.5432". Here, there are a maximum of 6 digits. This can be represented perfectly as "53.2812"

It can be represented perfectly in decimal arithmetic but NOT in binary arithmetic as used by modern computer systems.  

> CBigFloat bfResult;
> char      pcResult[1024]{};
> 
> bfResult = CBigFloat("3.4") + CBigFloat("7.238") + CBigFloat("23.1") + CBigFloat("19.5432");
> bfResult.ToString(pcResult, _countof(pcResult));
> ```
> 
> This results in "53.28119999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999968"
> 
> Is there a way to detect that the result should be rounded to "53.2812"?
> Every calculator on Earth will give you this number, but how do I make mpfr give me this number?

If you don't want 1024 bits of precision then decide what precision you want in your results and set the precision accordingly.  Every 3 digits of decimal precision you want needs approximately 10 bits of binary precision. So if you want the precision of a typical calculator set the binary precision to 50 bits, not 1024.  

Although I am trying to help you with your problem, this repository is about building MPFR on Windows and is not really the right place to discuss issues involved in using MPFR.

**Comment by SanderBouwhuis** [comment]
Ok, thanks Brian. I was hoping I was doing something wrong and that the function would return a 'sensible' result. I'll go to the mpfr forum and ask the question there.
PS
Many thanks for the Windows port. It is a great help when a double is not enough precision.
