### ISSUE TITLE
compiler turn on error c1189 as attached

### ISSUE THREAD

**Issue by zhouxs1023** [BrianGladman/mpfr#1]
OS:windows7
compiler:vs2017
target:x86
error as below:
![error c1189](https://user-images.githubusercontent.com/905931/189526713-354b2c96-1fd6-4463-8c8b-f07893874854.PNG)

**Comment by BrianGladman** [comment]
For x86, the define HAVE_LITTLE_ENDIAN should be set in your config,h file.  This error suggests that your version of config.h is either incorrect or is not properly located within the MPIR directory with which MPFR is being built.

**Comment by zhouxs1023** [comment]
I compile MPIR successfully;then can compiler MPFR successfully;Thanks you!
