### ISSUE TITLE
SAFE_ABS(type,x) from mpfr-impl.h (MSVC2015)

### ISSUE THREAD

**Issue by truedim** [BrianGladman/mpfr#1]
long x = -1;
unsigned long ax = SAFE_ABS(unsigned long, x); //ax=4294967295 in Release (Win32 and  x64)
std::cout << "ax=" << ax << std::endl;

In particular, this macro used in function mpfr_set_si_2exp which failed for negative arguments

working solution:
#define SAFE_ABS(type,x) ((type)((x) >= 0 ? (x) : -(x)))

There are many other places in MPFR with warning C4146 (unary minus operator applied to unsigned type, result still unsigned)

**Comment by BrianGladman** [comment]
HI, Bugs and change proposals for MPFR source code need to be reported on the MPFR mailing list at:  https://sympa.inria.fr/sympa/arc/mpfr

**Comment by truedim** [comment]
After upgrading to the latest "Visual Studio 2015 update 3 RC" problem was resolved.
Seems like it was some Visual Studio 2015 compiler optimization bug.
