### ISSUE TITLE
Typos in build files

### ISSUE THREAD

**Issue by AndrewSav** [BrianGladman/mpfr#15]
1) [These](https://github.com/BrianGladman/mpir/blob/ed5498adebaca588ef4a6a5de548571c1d81de3a/msvc/vs19/lib_mpir_gc/lib_mpir_gc.vcxproj#L101) seems to need to be 19 instead of 17 for vs2019 build

2) I'm not sure about [this one](https://github.com/BrianGladman/mpir/blob/ed5498adebaca588ef4a6a5de548571c1d81de3a/msvc/vs19/msbuild.bat#L22) but on my installation of VS2019 _without_ VS2017, the `15.0` folder does not have `msbuild.exe` in subfolder. I had to change `15.0` to `Current` to make it build.

Thank you!

**Comment by BrianGladman** [comment]
Hi Andrew,  I think you may have posted on my MPFR build by mistake since your comments appear to be related to MPIR rather than MPFR.   There was, as you suggest, the need to update the MPIR  msbuild.bat file for VS 2019,     Thanks for reporting this.

**Comment by BrianGladman** [comment]
I have updated the Visual Studio 2019 MPIR build to correct this issue but I don't have a machine with only VS 2019 installed.  It would hence be helpful if you could test the revised msbuild.bat file for VS 2019 on your system and report the result on my MPIR repository.  Thanks.

**Comment by AndrewSav** [comment]
@BrianGladman I'll endevour to test it within 48 hours, thanks. Mpir project has issues disable so it's not possible to open an issue there.

**Comment by AndrewSav** [comment]
@BrianGladman Also it seems that you did not do the change mentioned in number 1 of my post that is for lib_mpir_gc.vcxproj et al. The problem with `17` there is that wrong output folder is used and files built by vs19 end up in the vs17. Postbuild step also fails copying them out for reasons that are not entirly clear to me.

For you the best way to test _this_ issue is to run `git clean -xfd` because I'm suspecting that you have left-overs form prior VS2017 build that masked the issue. After that make the VS2019 build without building VS2017 first and observe if it fails. The msbuild.bat changes, I'll test.

**Comment by BrianGladman** [comment]
Hi Andrew, I wasn't aware that I did not have 'issues' enabled on MPIR.  I have enabled it now so we can cover further issues there.   Unfortunately the repository did not have my updated VS 2019 build files for the GC build, which I think is the cause of your problem. I have updated them now.

**Comment by AndrewSav** [comment]
The [bat file](https://github.com/BrianGladman/mpir/blob/master/msvc/vs19/msbuild.bat) still does not seem to work well on clean install. However,

```
msbuild.exe /p:Platform=win32 /p:Configuration=Release .\lib_mpir_gc\lib_mpir_gc.vcxproj
msbuild.exe /p:Platform=win32 /p:Configuration=Release .\lib_mpir_cxx\lib_mpir_cxx.vcxproj
```
does the job. I'll close the issue.
