### ISSUE TITLE
Cannot use gmp_sscanf with mpfr_t

### ISSUE THREAD

**Issue by SanderBouwhuis** [BrianGladman/mpfr#16]
### **gmp_sscanf exception error**
I'm trying to use gmp_sscanf with mpfr_t but am failing.
I want to get floating point numbers from strings where I also get the position of the end of the floating point.
```
int32 i32Len;
mpfr_t mpfrTest;
gmp_sscanf(-123.456 this is a test", "%Ff%n", mpfrTest, &i32Len);
```
The length is correctly stated as 8, but it either results in an exception error or in mpfrTest being '-1.5520000000'.

So, then I tried this:
```
int32 i32Len;
mpf_t mpfTest;
gmp_sscanf(-123.456 this is a test", "%Ff%n", mpfTest, &i32Len);
```
The length is again correctly stated as 8, but this also results in an exception error.

As far as I can tell this should work according to the documentation.
(see mpir.pdf page 74, third example:
```
/* to read say "topleft (1.55,-2.66)" */
mpf_t x, y;
char buf[32];
gmp_scanf ("%31s (%Ff,%Ff)", buf, x, y);
```

What am I doing wrong?

### **mpfr_set_str**
The mpfr_set_str function would be very useful, if not for the fact that for some strange reason the amount of chars read is not retained. Worse, the string MUST be '\0' terminated for the function to even work. My example of "-123.456 this is a test" would not even work!

### **workaround**
I now use this ugly workaround. Needless to say, this makes me a sad panda!!
```
// This function sets the CBigFloat to the supplied string
CBigFloat& CBigFloat::operator = (const int8 *pi8Num)
{
  try
  {
    CHECK_MEM_LEAKS

    // Clear the current value
    mpfr_set_zero(m_mpfr, 0);

    // Do we have valid parameters?
    if(pi8Num)
    {
      int8  *pi8End = nullptr, *pi8Temp;
      size_t szLen;

      // Get the length of the number
      strtod(pi8Num, &pi8End);
      if(pi8End >= pi8Num)
      {
        // Get the length
        szLen = pi8End - pi8Num + 1;

        // Allocate a buffer to hold the number
        pi8Temp = new int8[szLen];
        memmove(pi8Temp, pi8Num, szLen-1);
        pi8Temp[szLen-1] = '\0';

        // Set the number
        mpfr_set_str(m_mpfr, pi8Temp, 10, MPFR_RNDN);

        // Free the resources
        SAFE_DELETE_ARRAY(pi8Temp);
      }
    }
  }
  catch(...) { OnException(nullptr, __FILE__, __LINE__, __FUNCSIG__, __TIMESTAMP__, nullptr); }

  return *this;
}
```

**Comment by BrianGladman** [comment]
The main help forum for MPFR is here:

https://gforge.inria.fr/forum/forum.php?forum_id=436&group_id=136

I doubt that many will be able to respond to your post here.

**Comment by SanderBouwhuis** [comment]
Really?!? I've never heard of that forum?!?

I will try it there.

**Comment by BrianGladman** [comment]
This web page for MPFR gives details of the help forum: https://www.mpfr.org/ and points to:  https://sympa.inria.fr/sympa/arc/mpfr where the forum email address is given as mpfr@inria.fr .  I and others regularly use it when issues come up.

**Comment by SanderBouwhuis** [comment]
### **Solution**
Although the crashes still happen with the scanf functions, it turns out there is another function that will do what I need. If you use the mpfr_strtofr function, everything seems to work:

__MPFR_DECLSPEC int mpfr_strtofr (mpfr_ptr, const char *, char **, int, mpfr_rnd_t);
