### ISSUE TITLE
mpfr_asprintf() doesn't work on x86

### ISSUE THREAD

**Issue by abc983ft** [BrianGladman/mpfr#19]
The code below works fine on x64, but throws an exception on x86.

```
mpfr_float::default_precision(50);
mpfr_float pi("3.14159");
char *x;
mpfr_asprintf(&x, "%.2Rf", pi);
std::string s = std::string(x);
free(x);
```

**Comment by BrianGladman** [comment]
> The code below works fine on x64, but throws an exception on x86.
> 
> ```
> mpfr_float::default_precision(50);
> mpfr_float pi("3.14159");
> char *x;
> mpfr_asprintf(&x, "%.2Rf", pi);
> std::string s = std::string(x);
> free(x);
> ```
The documentation of mpfr_asprintf() indicates that the block of memory allocated by this function must be freed using mpfr_free_str().   Your code doesn't do this and is not therefore using the correct mpfr interface.  It might be an issue in MPFR but only if the exception is still present when the correct way of freeing the memory is used

**Comment by abc983ft** [comment]
thanks for the heads up about using mpfr_free_str(). The exception still happens (on Windows x86) as it occurs during the call to mpfr_asprintf().

exception file: vasprintf.c 
exception line:  1709 if (MPFR_UNLIKELY (MPFR_IS_SINGULAR (p)))
Exception thrown: read access violation.
**p** was 0xA8. occurred

**Comment by BrianGladman** [comment]
This test:
#include <stdio.h>
#include <mpfr.h>

int main()
{
    mpfr_t m;
    char* x;
    mpfr_init2(m, 50);
    mpfr_set_str(m, "3.14159", 10, MPFR_RNDN);
    mpfr_asprintf(&x, "%.2Rf", m);
    printf("%s", x);
    mpfr_free_str(x);
}

runs with no errors.    So it seems likely that the error lies elsewhere.  If you wish to continue with this report here you will need to give a full test program illustrating the issue and  full description of the circumstances in which it occurs.   Whether I can help further depends on what MPFR C++ interface you are using as I only use Pavel Holoborodko's MPFR C++ for work in C++.

**Comment by abc983ft** [comment]
Hi Brian, thanks for your reply. I was using the Boost Multiprecision wrapper.
I figured out the issue. mpfr_asprintf() would accept an argument of type boost::multiprecision::mpfr_float and on x64 everything worked, but it didn't work on x86. The correct thing to do was to call backend().data() on the boost::multiprecision::mpfr_float object to get the mpfr_t object that was wrapped and then pass that object to mpfr_asprintf().

`#include <iostream>
#include <boost/multiprecision/mpfr.hpp>

int main()
{
	mpfr_t m;
	char* x;
	mpfr_init2(m, 50);
	mpfr_set_str(m, "3.14159", 10, MPFR_RNDN);
	mpfr_asprintf(&x, "%.2Rf", m);
	printf("%s\n", x); //works
	mpfr_free_str(x);

	boost::multiprecision::mpfr_float::default_precision(50);
	boost::multiprecision::mpfr_float pi("3.14159");
	char *y;
	//mpfr_asprintf(&y, "%.2Rf", pi); //works on x64, doesn't work on x86
	mpfr_asprintf(&y, "%.2Rf", pi.backend().data()); //works on both x64 and x86
	std::cout << y << std::endl;
	mpfr_free_str(y);

	return 0;
}`
