### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by atelierw** [BrianGladman/mpfr#6]
You don't appear to care much, do you? Nothing is properly maintained. You are much more concerned with repeating where the license claim has to be displayed and stored than with doing things right.

**Comment by BrianGladman** [comment]
Your comment is both negative and unhelpful as it fails to identify any specific concerns.  If you have any specific issues please express them in a constructive manner.

**Comment by atelierw** [comment]
After struggling a lot I could build MPIR 3.1.5 by modifying your project files. However  it does not work properly when testing. 
Then with the trunk release "4.0 dev" you have here (why a dev release) , and after struggling as well a lot I could also build after experimenting all the Platform Toolsets (the only that builds is the VS 2012  Toolset).
It worked when testing 32-bit but crashes when testing 64-bit.

My question is? Do you build and test or just drop things and leave?

**Comment by BrianGladman** [comment]
Thank you for being more specific about the issues you face.   The answer to your question is that I track the development repository for MPFR at svn://scm.gforge.inria.fr/svn/mpfr/trunk.   Approximately weekly, I update the source code here to match that in that in the development repository and I then build and test the result with Visual Studio 2017 using a recent version of the Windows 10 platform toolset (currently I am using 10.0.15063.0).    I will modify the readme.txt file to make it clear that this is a development build.

**Comment by atelierw** [comment]
I can build both 32-bit and 64-bit, both Static Libraries and DLLs with Visual Studio 2017 - Windows XP (v141_xp).
32-bit both LIBs and DLLs work fine. 
64-bit crashes.

**Comment by BrianGladman** [comment]
Which version of MPIR are you using?   The *_ui and *_si functions can be problematic because of the fact that longs on Windows are always 32-bit types whereas MPIR uses 64-bit long long types on 64-bit Windows versions.  Are you invoking the crash in a particular way?

**Comment by atelierw** [comment]
I am using MPIR 3.0.
The functions I am invoking use 32-bit in both 32 and 64-bit, for example:
__MPFR_DECLSPEC int mpfr_mul_ui (mpfr_ptr, mpfr_srcptr, unsigned long,
                                 mpfr_rnd_t);

I had build MPFR 3.1.2 before. Although building is never easy because info is often misleading, once I built, the applications run. Now, they don't.

**Comment by BrianGladman** [comment]
Since you can build the libraries, this would seem to be an issue with MPFR itself.  There have been many changes in MPFR between version 3.1.2 and version 4 so it seems most likely that one or more of these may have caused the issue you are seeing.  I cannot directly test code for XP as I do not have any machines running XP.  But if you have a simple test case that demonstrates the crash, I could build and run it on Windows 10 to see if the issue is still present.

**Comment by atelierw** [comment]
Building with Visual Studio 2017 - Windows XP (v141_xp) does not require XP it should run fine in Windows 10 as well. The problem does not derive from there.

**Comment by atelierw** [comment]
[buildwarnings.zip](https://github.com/BrianGladman/mpfr/files/1203101/buildwarnings.zip)
One thing I notice is that huge quantity of type conversion warnings.

**Comment by BrianGladman** [comment]
I am using the development version of MPIR, which is very close to MPIR 3.0.0, so I doubt that this is the source of the problem.   I have just built MPFR with v141_xp and, apart from two tests that the linker would not link (tnrandom and tset_q), all the tests succeeded (I did not, however, rebuild MPIR with v141_xp)

**Comment by atelierw** [comment]
Using MPIR 2.7.2 does not cause crash when building 64-bit applications with MPFR.
But there still a huge quantity of type conversions warnings during the build of the MPFR libraries (as mentioned before).

**Comment by BrianGladman** [comment]
You are correct since nobody (at least nobody I know of) is testing all versions of MPIR that have ever existed with all versions of MPFR that have ever existed.   What I do to stay in control of my own use of these products is to build, test and use all development versions of MPIR, MPFR, etc. with the current 64-bit version of Windows using the current version of Visual Studio.   That alone is enough to keep me busy.

**Comment by atelierw** [comment]
I did not test all versions, I built 2.6 and today decided to build 2.7.2 to see if the problem was somewhat related to that and at least there is a correlation.

"By the way, if you are concerned about the huge number of warnings about type conversions when MPFR is built,"

I have always some difficulty in talk with people that appear to know a lot about computers that nobody use or are obsolete and have not the faintest idea of how things should work where it matters. I thought you were a privileged person to talk with them. If not let's the boat sink.

**Comment by BrianGladman** [comment]
Without a test case that demonstrates the crash, there is no way I can help further.

**Comment by atelierw** [comment]
I finished what I was trying to do today;
Static and Dynamic Libraries of MPFR 4.0 dev (built using MPIR 2.7.2)
MPIR 3.0 to be used alone as MPIR.

I will update everything in the website soon. The example is the same that is there. The website is in the BIO, I guess you have been there.

**Comment by BrianGladman** [comment]
I'm afraid I have no idea about the website to which you refer.

**Comment by atelierw** [comment]
All right, don't bother then.
There is also a thread in the [masm32 forum](http://masm32.com/board/index.php?topic=6438.0) about MPFR which I have started. I will update it soon with the latest MPFR/MPIR,
