### ISSUE TITLE
Would you please tell me how can I get config.h for Visual Studio 2015

### ISSUE THREAD

**Issue by ShifaSZ** [BrianGladman/mpfr#7]
When I open the solution under vc14 build the project, it reports missing file "config.h". I guess the config.h could be generated by a configure command. But I'm not sure how to do it. If you can provide the guidance for configuration for Visual Studio, it will be very appreciated. Thanks.

**Comment by BrianGladman** [comment]
Before you build mpfr you have to build the version of mpir with which mpfr will be linked.  Once this has been done mpfr will then pick up config.h from the related mpir directory.  

For example if you are building the x64\release version of mpfr static library, config.h will then be picked up from the directory: mpir\lib\x64\Release\ (which is where the mpir build puts it).

To use the mpfr build without any changes, the mpir and mpfr directories must: (a) have these names (i.e. no version number extensions etc.), and (b) they must themselves be in the same directory.   

If this is not the case you will need to modify the mpfr build configuration to match the locations and names that you are using.

**Comment by ShifaSZ** [comment]
Thanks for your prompt reply. I am trying to build lib_mpir project first. While I build it, the VS reports "cannot open source file 'config.h' ". When I look into the directory mpfr\lib\x64\Release\, I can find mpfr.h but no config.h in it. BTW, you mention the example directory "mpir\lib\x64\Release\". Is the "mpir" a typo of "mpfr" or really means mpir?

**Comment by BrianGladman** [comment]
No I really do mean mpir - MPFR uses the config.h file that is created when MPIR is built.  If building MPIR reports that it cant find config.h then the build has failed for some reason.  We need to work out why the MPIR build fails before worrying about MPFR.

**Comment by ShifaSZ** [comment]
Thanks. After I build MPIR, I copy everything in "mpir\lib\x64\Release\" to "mpfr\lib\x64\Release\". Then I build MPFR again. It succeeds.
