### ISSUE TITLE
Adding CMake files

### ISSUE THREAD

**Issue by xoviat** [BrianGladman/mpfr#8]
It would be nice if CMake files would be added so that we could use this repository for vcpkg.

**Comment by BrianGladman** [comment]
The problem if I add this is to work out how it will be maintained as I don't use CMake and cannot therefore maintain it.

**Comment by xoviat** [comment]
The ideal solution would be to switch to vcpkg to install your C++ libraries. I realize that sounds arrogant, but I do think that you would end up liking the experience. If not, I'll just close the PR.

**Comment by BrianGladman** [comment]
I am afraid I very little about CMake or vcpkg.    I am not that keen on CMake because the reference book by Kitware is very expensive and I didn't find the online material very easy to follow.    vcpkg does look interesting (and doesn't appear to require CMake) so I will take a look at it.

**Comment by xoviat** [comment]
> and doesn't appear to require CMake

This is a misunderstanding. vcpkg is CMake-driven. You don't need to install CMake because vcpkg will install it for you, but on the other hand, if everything works correctly, you don't actually need to know anything about CMake.

**Comment by BrianGladman** [comment]
I am quoting directly from: https://github.com/Microsoft/vcpkg and I would hope that it wouldn't install CMake without asking me!  I don''t like installing tools unless I have good documentation for them!.  You say that I don't need to know anything about CMake but you are asking me to add CMake code to one of my projects!  Adding code that I don't understand is not something I am keen to do!   But I will look again for a source of CMake reference documentation that does not cost "an arm and a leg".

**Comment by xoviat** [comment]
> you are asking me to add CMake code to one of my projects!

This is not correct. vcpkg will patch MSVC so that the include files and libraries will automatically be available (yes, patching MSVC is troublesome, but both tools are from MS so presumably they are in communication with the MSVC developers).

> I would hope that it wouldn't install CMake without asking me! 

vcpkg will not install cmake globally on your system. However, it will fetch various build tools (including CMake) if they are required to build (without asking you).

**Comment by xoviat** [comment]
Closing for now.
